### ISSUE TITLE
After installing brotli it broke all my websites

### ISSUE THREAD

**Issue by petriichuk** [google/ngx_brotli#107]
Does it change something in nginx config? How to disable and remove all changes?

**Comment by eustas** [comment]
Hello, could you elaborate a bit, what does "install" mean?
Thanks.

**Comment by petriichuk** [comment]
Done this steps 
https://computingforgeeks.com/how-to-enable-gzip-brotli-compression-for-nginx-on-linux/

sudo apt-add-repository -y ppa:hda-me/nginx-stable
sudo apt-get update
sudo apt-get install brotli nginx nginx-module-brotli

**Comment by eustas** [comment]
Unfortunately, we don't know what package `nginx-module-brotli` in Personal Package Archive `hda-me` does.
Also note, that `nginx` package could have been installed from the same PPA.

Please file an issue at https://bugs.launchpad.net/~hda-me
