### ISSUE TITLE
Do not send “Content-Encoding: br” header or HEAD requests

### ISSUE THREAD

**Issue by dilyanpalauzov** [google/ngx_brotli#108]
On HEAD requests (fetch javascript API), [Firefox sends](https://bugzilla.mozilla.org/show_bug.cgi?id=1663310) the “Accept-Encoding:gzip, deflate, br”.

I am not sure, if this is a problem of ngx_brotli, or nginx, but the server sends back the “content-encoding: br” headers.

Since HEAD answers do not have body, describing the content-encoding of the body is suboptimal.

**Comment by kapouer** [comment]
There is a misunderstanding about HEAD requests. Remember that:
> The HTTP HEAD method requests the headers that would be returned if the HEAD request's URL was instead requested with the HTTP GET method.
> For example, if a URL might produce a large download, a HEAD request could read its Content-Length header to check the filesize without actually downloading the file.
[Source](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD)

**Comment by dilyanpalauzov** [comment]
Indeed: on HEAD requests these is no (content-encoded) body in the response.  Or you mean, that by sending both “Content-Encoding” and “Content-Length”, the client can get the length of the encoded (and not sent) body? Who needs why this information?

**Comment by eustas** [comment]
Client might send HEAD request e.g. to make sure that server supports "br" Content-Encoding for the given entry.

**Comment by eustas** [comment]
RFC 7231: "The server SHOULD send the same header fields in response to a HEAD request as it would have sent if the request had been a GET".
