### ISSUE TITLE
Update brotli to v1.0.9

### ISSUE THREAD

**Issue by hkraal** [google/ngx_brotli#109]
Brotli should be updated to the patched version;

> Version 1.0.9 contains a fix to "integer overflow" problem. This happens when "one-shot" decoding API is used (or input chunk for streaming API is not limited), input size (chunk size) is larger than 2GiB, and input contains uncompressed blocks. After the overflow happens, memcpy is invoked with a gigantic num value, that will likely cause the crash.

PR is underway

**Comment by eustas** [comment]
Fixed bug does not affect the plugin... But OK.
