### ISSUE TITLE
Precendence over gzip

### ISSUE THREAD

**Issue by toastal** [google/ngx_brotli#11]
My Firefox browser is set to `Accept-Encoding: br, gzip, deflate`. I have both gzip and brotli turned on on the server, but gzip seems to take precedence over brotli when I view `Content-Encoding` for the response. If I turn off gzip on the server or take gzip off the Accept-Encoding from the browser's request, I'll get "br" as the Content-Encoding. Is there a way to change this?

Latest pull on brotli & ngx_brotli, nginx 1.9.7.rc1 (openresty)
Firefox v45.0a

**Comment by PiotrSikora** [comment]
I cannot replicate this (neither with vanilla nginx-1.9.7 nor with ngx_openresty-1.9.7.1).

What website are you testing this with? Do you have any proxies or CDN in between?

**Comment by toastal** [comment]
I was testing my personal page placeholder @ https://toast.al/ . There's no proxies/CDN between my content and the user. According to my config, the HTML and CSS should be using brotli. I also have gzip and brotli static both enabled..

**Comment by toastal** [comment]
Actually, here's the relevant config lines:

```
    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_static on;

    brotli on;
    brotli_types text/html text/css text/javascript application/javascript application/json image/svg+xml;
    brotli_static on;
```

**Comment by toastal** [comment]
If it helps, here's my source for the site as well as my build steps for the server in the README: https://bitbucket.org/toastal/toast.al-social-page/src

**Comment by PiotrSikora** [comment]
Are you sure your that web application doesn't send compressed (read: gzipped) responses?

`ngx_brotli` doesn't re-compress already compressed responses, so if it's gzipped before reaching nginx, it will be passed to the client as such.

**Comment by toastal** [comment]
I'm not 100% sure what you're asking about compressed responses and apps...

The two files are static, a `.html` file and a `.css` file. There's no app being proxied to or anything like that. Both files however *do* have a precompressed version for `gzip_static` and `brotli_static`.

```
Σ /v/w/t/dist (master=) tree .
.
├── css
│   ├── main.css
│   ├── main.css.br
│   └── main.css.gz
├── fonts
│   └── fantasque-sans-mono
│       ├── FantasqueSansMono-BoldItalic.woff
│       ├── FantasqueSansMono-BoldItalic.woff2
│       ├── FantasqueSansMono-Bold.woff
│       ├── FantasqueSansMono-Bold.woff2
│       ├── FantasqueSansMono-Italic.woff
│       ├── FantasqueSansMono-Italic.woff2
│       ├── FantasqueSansMono-Regular.woff
│       └── FantasqueSansMono-Regular.woff2
├── index.html
├── index.html.br
├── index.html.gz
└── robots.txt

3 directories, 15 files
```

**Comment by PiotrSikora** [comment]
Well, I don't know your `nginx.conf` (can you share it, please? Ideally, just minimal version that you're able to replicate this with), so I'm trying to guess what might be the source of this weird behavior.

Brotli takes precedence over gzip in all my tests...

**Comment by toastal** [comment]
```
worker_processes  4;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_static on;

    brotli on;
    brotli_types text/html text/css text/javascript application/javascript application/json image/svg+xml;
    brotli_static on;

    server_tokens off;

    server {
        listen       80;
        server_name  toast.al;
	rewrite ^ https://$server_name$request_uri? permanent;

        ...
    }


    # HTTPS server
    
    server {
        listen       443 default_server ssl http2;
        server_name  toast.al;

        add_header X-Frame-Options SAMEORIGIN;
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options nosniff;
        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";

        ... ssl stuff ...

        location / {
            root  /var/www/toast.al-social-page/dist;
            index index.html index.htm;
        }
    }

    server {
       listen 80;
       listen 443 ssl http2;
       server_name www.toast.al;
       return 301  $scheme://toast.al$request_uri;
    }

}
```

**Comment by PiotrSikora** [comment]
I still cannot replicate this issue, even when using your config...

Could you give me the git commit of `ngx_brotli` that you've checked out?

Also, could you provide a [debug log](http://nginx.org/en/docs/debugging_log.html) of the gzipped request?

**Comment by toastal** [comment]
Derp. So it wasn't this module. The output of `bro` to a `*.br` file doesn't come with read permissions. Sorry about that--I saw the files in the directory and assumed permissions.

**Comment by Angristan** [comment]
Ho to set `Accept-Encoding: br` ?

**Comment by toastal** [comment]
If you're asking "how" to set it from the browser, only the Firefox 44+ and latest dev Chromium (behind a flag) support brotli. You'll need one of the supported browsers and they will add the accepted encoding by default.

**Comment by Angristan** [comment]
Okay I updated Firefox to version 44 and I have this : `Accept-Encoding :"gzip, deflate, br"`
Is this the good order ?

**Comment by toastal** [comment]
Order shouldn't matter. But if you're interested, it can be modified at `about:config` rule `network.http.accept-encoding.secure`.

**Comment by Angristan** [comment]
Thanks. I do I know if my web server is correctly configured with Brotli ?

**Comment by toastal** [comment]
How do you know? You can inspect a resource from Firefox's Network tab that should have the encoding. In the response headers of that resource you should see `Content-Encoding: "br"`.

**Comment by Angristan** [comment]
I don't have it :/ 
![screenshot_01-02-2016_01qdj4hy](https://cloud.githubusercontent.com/assets/11699655/12724221/36c0512c-c90d-11e5-8943-fc6eae00b7cf.png)

**Comment by toastal** [comment]
![headers-brotli](https://cloud.githubusercontent.com/assets/561087/12733209/cadc4986-c8f6-11e5-9bfb-073439da885c.png) Mine's working fine.
