### ISSUE TITLE
Error while compiling in Debian 8

### ISSUE THREAD

**Issue by Angristan** [google/ngx_brotli#12]
Hello, 

I am using deb-src from the Nginx mainline repo. (nginx is compiling correctly)
I installed libbrotli, but when doing `dpkg-buldpackage -b`, i get this : 
```
make[1]: Entering directory '/opt/nginx/1.9.10/nginx-1.9.10'
dh_strip --dbg-package=nginx-dbg
make[1]: Leaving directory '/opt/nginx/1.9.10/nginx-1.9.10'
   dh_makeshlibs
   dh_shlibdeps
dpkg-shlibdeps: erreur: pas d'information de dépendance trouvée pour /usr/local/lib/libbrotlienc.so.1 (utilisé par debian/nginx/usr/sbin/nginx)
Indication: vérifiez que la bibliothèque provienne bien d'un paquet.
dh_shlibdeps: dpkg-shlibdeps -Tdebian/nginx.substvars debian/nginx/usr/sbin/nginx-debug debian/nginx/usr/sbin/nginx returned exit code 2
debian/rules:11: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: erreur: debian/rules binary a produit une erreur de sortie de type 2
```

**Comment by PiotrSikora** [comment]
I'm afraid that you're reporting this in a wrong place (and with a wrong title).

While there is clearly an issue with how `libbrotli` dependency is handled in the script you're using to build `nginx` binary, it's an issue with that script and not with `ngx_brotli` module... I'm afraid that I'm not in a position to help you with it.

**Comment by Angristan** [comment]
The README says : 

> Installation
> 
> $ cd nginx-1.x.x
> $ ./configure --add-module=/path/to/ngx_brotli
> $ make && make install

That's exactly what I am doing

**Comment by PiotrSikora** [comment]
That's not at all what you've pasted in your original post. Neither of those commands calls `dpkg-buldpackage` or `dh_shlibdeps`.

**Comment by lGuillaume124** [comment]
Hi @Angristan 

Under Debian you can add this in ``nginx-1.9.10/debian/rules``:

```make
override_dh_shlibdeps:                                                          
    dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info
```
