### ISSUE TITLE
Statically compiled installation fails

### ISSUE THREAD

**Issue by ochedru** [google/ngx_brotli#148]
It was working fine until recent upgrade of brotli:

```
...
58.50 /usr/bin/ld: cannot find -lbrotlienc: No such file or directory
58.50 collect2: error: ld returned 1 exit status
58.50 make[1]: *** [objs/Makefile:252: objs/nginx] Error 1
58.50 make[1]: Leaving directory '/tmp/nginx-1.24.0'
58.51 make: *** [Makefile:13: install] Error 2
```

**Comment by NicolasCARPi** [comment]
Works fine for me, my usual build script works with the latest commit. Maybe it could help to provide more context, such as which commands are being used to compile/clone/etc...

**Comment by wyattoday** [comment]
We’ve had the exact same problem.

it’s related to the upstream Brotli dependency dropping support for Makefiles, but this project hasn’t been updated to use CMake and build / link to the correct static libs.

Kinda a mess if you ask me. We wasted a couple hours on it yesterday, came close to a build fix, but ran out of time.

We might spend some time looking for a fix next week. But we also have bigger fish to fry. We might also just drop dynamic brotli support (might be a better use of our resources).

**Comment by ochedru** [comment]
> Works fine for me, my usual build script works with the latest commit. Maybe it could help to provide more context, such as which commands are being used to compile/clone/etc...

My bad. Here are the commands to reproduce (to run from e.g. a debian:stable-slim container):
```bash
#!/bin/bash
apt-get update
apt-get --assume-yes --no-install-recommends install gnupg dirmngr curl unzip ca-certificates procps build-essential git zlib1g-dev libpcre3-dev
export nginx_version=1.24.0
cd /tmp
curl --silent -O https://nginx.org/download/nginx-$nginx_version.tar.gz
tar xzf nginx-$nginx_version.tar.gz
git clone --recursive https://github.com/google/ngx_brotli
cd nginx-$nginx_version
./configure --add-module=/tmp/ngx_brotli 
make
```

**Comment by wyattoday** [comment]
> try `apt install libbrotli-dev`

Then you’re not building with the included brotli dependency. You’re bringing in whatever out-of-date brotli dependency the OS has included.

Building with the included brotli is broken.

**Comment by DragonicDefson** [comment]
Good evening,

For everyone searching for a temporary solution, just got it fixed, it's a dirty fix but it works from my end.
This is in a Dockerfile, but it should work on a barebone as long as you pull the latest update with git and checkout with the second latest hash.

`FROM alpine:latest
WORKDIR /usr/src/app
ENV NGINXVER=1.25.2
ENV NGXBROTLIFIX=6e975bcb015f62e1f303054897783355e2a877dc
ENV NGINXMODDIR=/tmp/nginx/brotli-nginx-module
RUN apk add --update --upgrade --no-cache linux-headers build-base git pcre-dev openssl-dev zlib-dev ca-certificates curl gnupg
RUN curl https://nginx.org/keys/nginx_signing.key -o nginx_signing.key && \
    gpg --import nginx_signing.key && \
    mkdir /tmp/nginx && \
    curl -SL https://nginx.org/download/nginx-${NGINXVER}.tar.gz -o nginx.tar.gz && \
    tar -xzvf nginx.tar.gz -C /tmp/nginx --strip-components=1 && \
    rm nginx.tar.gz && git clone https://github.com/google/ngx_brotli.git ${NGINXMODDIR} && cd ${NGINXMODDIR} && git checkout ${NGXBROTLIFIX} && git submodule update --init --recursive && cd /tmp/nginx
WORKDIR /tmp/nginx
RUN ./configure \
        --add-module=${NGINXMODDIR} \
        --prefix=/etc/nginx/ \
        --sbin-path=/usr/sbin/nginx \
        --conf-path=/etc/nginx/nginx.conf \
        --error-log-path=/var/log/nginx/error.log \
        --pid-path=/run/nginx.pid \
        --lock-path=/run/nginx.lock \
        --user=nginx \
        --group=nginx \
        --with-file-aio \
        --with-ipv6 \
        --with-http_ssl_module \
        --with-http_realip_module \
        --with-http_addition_module \
        --with-http_sub_module \
        --with-http_gzip_static_module \
        --with-http_auth_request_module \
        --with-http_secure_link_module \
        --with-http_stub_status_module \
        --http-log-path=/var/log/nginx/access.log \
        --http-client-body-temp-path=/var/cache/nginx/client_temp \
        --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
        --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
        --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
        --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
        --with-cpu-opt=amd64 \
        --with-pcre && \
        make && make install && \
        mkdir /var/cache/nginx && \
        mkdir /var/cache/nginx/client_temp && \
        mkdir /var/cache/nginx/proxy_temp && \
        mkdir /var/cache/nginx/fastcgi_temp && \
        mkdir /var/cache/nginx/uwsgi_temp && \
        mkdir /var/cache/nginx/scgi_temp && \
        touch /run/nginx.pid && \
        addgroup -S nginx && adduser -S nginx -G nginx
ADD config /etc/nginx
ADD certs /var/lib/nginx/certs
RUN chmod -R 400 /var/lib/nginx/certs && mkdir -p /usr/share/nginx/logs
CMD ["nginx", "-g", "daemon off;"]
`

**Comment by super-vip** [comment]
I also encountered the same problem!

nginx version: 1.24.0 and 1.25.2

......
objs/addon/filter/ngx_http_brotli_filter_module.o \
objs/addon/static/ngx_http_brotli_static_module.o \
objs/ngx_modules.o \
-ldl -lpthread -lpthread -lcrypt -lbrotlienc -lm ../pcre-8.45/.libs/libpcre.a ../openssl-1.1.1v/.openssl/lib/libssl.a ../openssl-1.1.1v/.openssl/lib/libcrypto.a -ldl -lpthread ../zlib-1.3/libz.a \
-Wl,-E
/bin/ld: 找不到 -lbrotlienc
collect2: 错误：ld 返回 1
make[1]: *** [objs/nginx] 错误 1
make[1]: 离开目录“/seeyon/scripts/nginx-1.25.2”
make: *** [build] 错误 2
......


git clone https://github.com/google/ngx_brotli
cd ngx_brotli && git submodule update --init

cd ../nginx-1.25.2 && ./configure \
--prefix=/apps/nginx \
--modules-path=/apps/nginx/modules \
--with-compat \
--with-stream \
--with-stream_ssl_module \
--with-stream_realip_module \
--with-stream_ssl_preread_module \
--with-threads \
--with-file-aio \
--with-http_ssl_module \
--with-http_v2_module \
--with-http_realip_module \
--with-http_addition_module \
--with-http_sub_module \
--with-http_dav_module \
--with-http_gunzip_module \
--with-http_gzip_static_module \
--with-http_auth_request_module \
--with-http_random_index_module \
--with-http_secure_link_module \
--with-http_degradation_module \
--with-http_slice_module \
--with-http_stub_status_module \
--with-zlib=../zlib-1.3 \
--with-pcre=../pcre-8.45 \
--with-openssl=../openssl-1.1.1v \
--add-module=../ngx_brotli

**Comment by buobuk** [comment]
> It was working fine until recent upgrade of brotli:
> 
> ```
> ...
> 58.50 /usr/bin/ld: cannot find -lbrotlienc: No such file or directory
> 58.50 collect2: error: ld returned 1 exit status
> 58.50 make[1]: *** [objs/Makefile:252: objs/nginx] Error 1
> 58.50 make[1]: Leaving directory '/tmp/nginx-1.24.0'
> 58.51 make: *** [Makefile:13: install] Error 2
> ```

I had the same problem

**Comment by iwebroot** [comment]
Hello,
I had a same problem with nginx v1.25.2.

**Comment by rosebe** [comment]
> > try `apt install libbrotli-dev`
> 
> Then you’re not building with the included brotli dependency. You’re bringing in whatever out-of-date brotli dependency the OS has included.
> 
> Building with the included brotli is broken.
> 
> This commit removes make files from brotli: [google/brotli@d1faddd](https://github.com/google/brotli/commit/d1fadddc940a23de3fad34c02879d7cfa6f86460)
> 
> This commit brings in the latest brotli (without updating the build files): [8f726ea](https://github.com/google/ngx_brotli/commit/8f726ea6614eb5541812647a673abd8f66eb4660)
> 
> Those 2 commit break things. So either bring back Make files to brotli and/or fixing this repository to build the included brotli using CMake.

> My solution is to restore the original file roughly.
https://github.com/rosebe/brotli/commit/4e1a5d026b813e7a16d5604ce3defabefc2493cb  and  https://github.com/rosebe/brotli/commit/b81f9e1b43005136da2da5ad028e566eb13ae687

git clone https://github.com/google/ngx_brotli
cd ngx_brotli && git submodule update --init
cd deps
rm -rf brotli
git clone -b brotli-fix https://github.com/rosebe/brotli.git
cd ../..

cd ./nginx-1.25.2 && ./configure
--prefix=/apps/nginx
--modules-path=/apps/nginx/modules
--with-compat
--with-stream
--with-stream_ssl_module
--with-stream_realip_module
--with-stream_ssl_preread_module
--with-threads
--with-file-aio
--with-http_ssl_module
--with-http_v2_module
--with-http_realip_module
--with-http_addition_module
--with-http_sub_module
--with-http_dav_module
--with-http_gunzip_module
--with-http_gzip_static_module
--with-http_auth_request_module
--with-http_random_index_module
--with-http_secure_link_module
--with-http_degradation_module
--with-http_slice_module
--with-http_stub_status_module
--with-zlib=../zlib-1.3
--with-pcre=../pcre-8.45
--with-openssl=../openssl-1.1.1v
--add-module=../ngx_brotli

**Comment by DragonicDefson** [comment]
Imagine trying so desperately to be the temporary solution provider that you:

Make a complete repo with the second latest commit source code which is just a waste of server resources,
just to provide a cleaner git pull link.
And apparently eventually you're marked as the temporary solution provider.

But you don't really have to look closely to see it's thievery.

**Comment by wyattoday** [comment]
### Fixed build

I've submitted a PR that fixes this bug: 

In the meantime here's the real-fix (not pulling in old commits). First get `ngx_brotli` and build the dependencies:

(Note if you don't have `cmake` on your system you'll first need to install it using something like `apt-get install cmake`)


```
git clone --recurse-submodules -j8 https://github.com/wyattoday/ngx_brotli
cd ngx_brotli/deps/brotli
mkdir out && cd out
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS="-Ofast -m64 -march=native -mtune=native -flto -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections" -DCMAKE_CXX_FLAGS="-Ofast -m64 -march=native -mtune=native -flto -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections" -DCMAKE_INSTALL_PREFIX=./installed ..
cmake --build . --config Release --target brotlienc
cd ../../../..
```

Then build NGINX:

```
cd nginx-1.x.x
export CFLAGS="-m64 -march=native -mtune=native -Ofast -flto -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections"
export LDFLAGS="-m64 -Wl,-s -Wl,-Bsymbolic -Wl,--gc-sections"
./configure --add-module=/path/to/ngx_brotli
make && make install
```

**Comment by vladbondarenko** [comment]
Hello,
Will reopen this issue as i got an error during the build with fix from https://github.com/google/ngx_brotli/issues/148#issuecomment-1706648408

```
objs/src/http/modules/ngx_http_upstream_keepalive_module.o \
objs/src/http/modules/ngx_http_upstream_zone_module.o \
objs/src/http/modules/ngx_http_stub_status_module.o \
objs/src/misc/ngx_google_perftools_module.o \
objs/addon/filter/ngx_http_brotli_filter_module.o \
objs/addon/static/ngx_http_brotli_static_module.o \
objs/ngx_modules.o \
-Wl,-E -ldl -lpthread -lcrypt -L/root/ngx_brotli/deps/brotli/c/../out -lbrotlienc -lbrotlicommon -lm -lpcre -lssl -lcrypto -ldl -lpthread -lz -lprofiler \
-Wl,-E
/tmp/ccZrUj2n.ltrans2.ltrans.o: In function `ngx_http_brotli_filter_close':
<artificial>:(.text+0x7c21): undefined reference to `BrotliEncoderDestroyInstance'
/tmp/ccZrUj2n.ltrans2.ltrans.o: In function `ngx_http_brotli_body_filter':
<artificial>:(.text+0x7f00): undefined reference to `BrotliEncoderCreateInstance'
<artificial>:(.text+0x7f1e): undefined reference to `BrotliEncoderSetParameter'
<artificial>:(.text+0x80fa): undefined reference to `BrotliEncoderHasMoreOutput'
<artificial>:(.text+0x810b): undefined reference to `BrotliEncoderIsFinished'
<artificial>:(.text+0x81a2): undefined reference to `BrotliEncoderCompressStream'
<artificial>:(.text+0x8213): undefined reference to `BrotliEncoderTakeOutput'
<artificial>:(.text+0x8324): undefined reference to `BrotliEncoderCompressStream'
<artificial>:(.text+0x8354): undefined reference to `BrotliEncoderIsFinished'
<artificial>:(.text+0x83a2): undefined reference to `BrotliEncoderSetParameter'
collect2: error: ld returned 1 exit status
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory `/root/nginx-1.25.2'
make: *** [build] Error 2
The command '/bin/sh -c cd /root/nginx-1.25.2 && export CFLAGS="-m64 -march=native -mtune=native -Ofast -flto -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections" && export LDFLAGS="-m64 -Wl,-s -Wl,-Bsymbolic -Wl,--gc-sections" && ./configure --add-module=/root/ngx_brotli --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/var/run/nginx.pid --lock-path=/var/lock/subsys/nginx --user=nginx --group=nginx --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module --with-http_stub_status_module --with-http_perl_module=dynamic --with-http_auth_request_module --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-google_perftools_module --with-debug --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic' --with-ld-opt=' -Wl,-E' && make && make install && nginx -V' returned a non-zero code: 2
```
nginx-1.25.2
cmake3 version 3.17.5

Any ideas how to fix this?

Thanks.

**Comment by wyattoday** [comment]
Read the README.

**Comment by vladbondarenko** [comment]
Unfortunately thats didnt help :(

Adding part of Dockerfile that is building FROM amazonlinux:2 (centos7)

```
RUN cd /root && wget http://nginx.org/download/nginx-1.25.2.tar.gz && tar xzf nginx-1.25.2.tar.gz

RUN cd /root && git clone --recurse-submodules -j8 https://github.com/google/ngx_brotli

RUN mkdir /root/ngx_brotli/deps/brotli/out && cd /root/ngx_brotli/deps/brotli/out && cmake3 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS="-Ofast -m64 -march=native -mtune=native -flto -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections" -DCMAKE_CXX_FLAGS="-Ofast -m64 -march=native -mtune=native -flto -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections" -DCMAKE_INSTALL_PREFIX=./installed .. && cmake3 --build . --config Release --target brotlienc

RUN cd /root/nginx-1.25.2 && export CFLAGS="-m64 -march=native -mtune=native -Ofast -flto -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections" && export LDFLAGS="-m64 -Wl,-s -Wl,-Bsymbolic -Wl,--gc-sections" && ./configure --add-module=/root/ngx_brotli --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/var/run/nginx.pid --lock-path=/var/lock/subsys/nginx --user=nginx --group=nginx --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module --with-http_stub_status_module --with-http_perl_module=dynamic --with-http_auth_request_module --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-google_perftools_module --with-debug --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic' --with-ld-opt=' -Wl,-E' && make && make install && nginx -V
```

Error stil the same:

```
objs/ngx_modules.o \
-Wl,-E -ldl -lpthread -lcrypt -L/root/ngx_brotli/deps/brotli/c/../out -lbrotlienc -lbrotlicommon -lm -lpcre -lssl -lcrypto -ldl -lpthread -lz -lprofiler \
-Wl,-E
/tmp/ccFuLZ49.ltrans2.ltrans.o: In function `ngx_http_brotli_filter_close':
<artificial>:(.text+0x7c31): undefined reference to `BrotliEncoderDestroyInstance'
/tmp/ccFuLZ49.ltrans2.ltrans.o: In function `ngx_http_brotli_body_filter':
<artificial>:(.text+0x7f10): undefined reference to `BrotliEncoderCreateInstance'
<artificial>:(.text+0x7f2e): undefined reference to `BrotliEncoderSetParameter'
<artificial>:(.text+0x810a): undefined reference to `BrotliEncoderHasMoreOutput'
<artificial>:(.text+0x811b): undefined reference to `BrotliEncoderIsFinished'
<artificial>:(.text+0x81b2): undefined reference to `BrotliEncoderCompressStream'
<artificial>:(.text+0x8223): undefined reference to `BrotliEncoderTakeOutput'
<artificial>:(.text+0x8334): undefined reference to `BrotliEncoderCompressStream'
<artificial>:(.text+0x8364): undefined reference to `BrotliEncoderIsFinished'
<artificial>:(.text+0x83b2): undefined reference to `BrotliEncoderSetParameter'
collect2: error: ld returned 1 exit status
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory `/root/nginx-1.25.2'
make: *** [build] Error 2
```

**Comment by kn007** [comment]
same issue here.
nginx 1.25.3

```
/data/src/ngx_brotli/filter/ngx_http_brotli_filter_module.c:555: error: undefined reference to 'BrotliEncoderCreateInstance'
/data/src/ngx_brotli/filter/ngx_http_brotli_filter_module.c:563: error: undefined reference to 'BrotliEncoderSetParameter'
/data/src/ngx_brotli/filter/ngx_http_brotli_filter_module.c:572: error: undefined reference to 'BrotliEncoderSetParameter'
/data/src/ngx_brotli/filter/ngx_http_brotli_filter_module.c:628: error: undefined reference to 'BrotliEncoderDestroyInstance'
/data/src/ngx_brotli/filter/ngx_http_brotli_filter_module.c:452: error: undefined reference to 'BrotliEncoderIsFinished'
/data/src/ngx_brotli/filter/ngx_http_brotli_filter_module.c:492: error: undefined reference to 'BrotliEncoderCompressStream'
/data/src/ngx_brotli/filter/ngx_http_brotli_filter_module.c:423: error: undefined reference to 'BrotliEncoderHasMoreOutput'
/data/src/ngx_brotli/filter/ngx_http_brotli_filter_module.c:425: error: undefined reference to 'BrotliEncoderTakeOutput'
/data/src/ngx_brotli/filter/ngx_http_brotli_filter_module.c:463: error: undefined reference to 'BrotliEncoderCompressStream'
/data/src/ngx_brotli/filter/ngx_http_brotli_filter_module.c:628: error: undefined reference to 'BrotliEncoderDestroyInstance'
/data/src/ngx_brotli/filter/ngx_http_brotli_filter_module.c:437: error: undefined reference to 'BrotliEncoderIsFinished'
/data/src/ngx_brotli/filter/ngx_http_brotli_filter_module.c:628: error: undefined reference to 'BrotliEncoderDestroyInstance'
/data/src/ngx_brotli/filter/ngx_http_brotli_filter_module.c:628: error: undefined reference to 'BrotliEncoderDestroyInstance'
```
