### ISSUE TITLE
Statically compiled failure on debian 11 ARM

### ISSUE THREAD

**Issue by buobuk** [google/ngx_brotli#152]
Works fine for AMD， but not on the ARM platform.

`root@debian:~/nginx/ngx_brotli/deps/brotli/out# 
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_C_FLAGS="-Ofast -m64 -march=native -mtune=native -flto -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections" -DCMAKE_CXX_FLAGS="-Ofast -m64 -march=native -mtune=native -flto -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections" -DCMAKE_INSTALL_PREFIX=./installed ..

-- The C compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - broken
CMake Error at /usr/share/cmake-3.18/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /root/nginx/ngx_brotli/deps/brotli/out/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/gmake cmTC_4d547/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_4d547.dir/build.make CMakeFiles/cmTC_4d547.dir/build
    gmake[1]: Entering directory '/root/nginx/ngx_brotli/deps/brotli/out/CMakeFiles/CMakeTmp'
    Building C object CMakeFiles/cmTC_4d547.dir/testCCompiler.c.o
    /usr/bin/cc   -Ofast -m64 -march=native -mtune=native -flto -funroll-loops -ffunction-sections -fdata-sections -Wl,--gc-sections  -o CMakeFiles/cmTC_4d547.dir/testCCompiler.c.o -c /root/nginx/ngx_brotli/deps/brotli/out/CMakeFiles/CMakeTmp/testCCompiler.c
    cc: error: unrecognized command-line option ‘-m64’
    gmake[1]: *** [CMakeFiles/cmTC_4d547.dir/build.make:85: CMakeFiles/cmTC_4d547.dir/testCCompiler.c.o] Error 1
    gmake[1]: Leaving directory '/root/nginx/ngx_brotli/deps/brotli/out/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:140: cmTC_4d547/fast] Error 2
    
    
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:11 (project)

-- Configuring incomplete, errors occurred!
See also "/root/nginx/ngx_brotli/deps/brotli/out/CMakeFiles/CMakeOutput.log".
See also "/root/nginx/ngx_brotli/deps/brotli/out/CMakeFiles/CMakeError.log".`

**Comment by wyattoday** [comment]
Drop the -m64 option on Arm. The error is telling you exactly what to do.

**Comment by buobuk** [comment]
> Drop the -m64 option on Arm. The error is telling you exactly what to do.

thanks, well done with that

`cd ngx_brotli/deps/brotli`
`mkdir out && cd out`
`cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./installed ..`
`cmake --build . --config Release --target brotlienc`
`cd nginx-1.24.0`
`
./configure \
--user=www \
--group=www \
--prefix=/usr/local/nginx \
--pid-path=/run/nginx.pid \
--with-http_v2_module \
--with-http_ssl_module \
--with-http_realip_module \
--with-http_gzip_static_module \
--with-http_secure_link_module \
--with-stream \
--with-stream_ssl_module \
--with-stream_ssl_preread_module \
--with-stream_realip_module \
--add-module=/path/to/ngx_brotli
`
`make && make install`
