### ISSUE TITLE
Still "make[1]: Nothing to be done for 'modules'" after PR

### ISSUE THREAD

**Issue by tuxtorials** [google/ngx_brotli#153]
After the merge to master of this [PR](https://github.com/google/ngx_brotli/pull/150) the issue is still the same [as here](https://github.com/google/ngx_brotli/issues/149).

When trying to compile for dynamically loading, the following error appears:
```
make -f objs/Makefile modules
make[1]: Entering directory '/opt/nginx-1.24.0'
make[1]: Nothing to be done for 'modules'.
make[1]: Leaving directory '/opt/nginx-1.24.0'
```

**Comment by wyattoday** [comment]
See the updated read me. The brotli dependency needs to be built first. The nginx “config files” are too simple to automate that.

hence a new separate step.

**Comment by mitap13** [comment]
```
cannot find -lbrotlienc: No such file or directory
cannot find -lbrotlicommon: No such file or directory
```
I am also still getting the errors below when trying to dynamically add the module. 
There isn't any update on dynamically loading part of the readme. Am I missing something?

**Comment by wyattoday** [comment]
Just use the static modules. They’re faster and smaller.

or, if you’re determined to use the dynamic modules, build brotli first (see the static modules instructions)

**Comment by tuxtorials** [comment]
> or, if you’re determined to use the dynamic modules, build brotli first (see the static modules instructions)

that doesnt work. I've builded brotli first and then headed to dynamically loading and the issue is still the same:
```make[1]: Nothing to be done for 'modules``` on `make modules`.

**Comment by tuxtorials** [comment]
I think I had a typo somewhere. Now it actually works properly. Thank you.
