### ISSUE TITLE
Brotli throwing errors on make modules: Ubuntu 22.04

### ISSUE THREAD

**Issue by malee1975** [google/ngx_brotli#155]
Hi,

Until a few weeks ago, NGX Brotli was installing okay on Ubuntu 22.04. 

I was compiling it as a dynamic module for NGINX 1.18.0.

After running make modules. The following error now appears:

/usr/bin/ld: cannot find -lbrotlienc: No such file or directory
/usr/bin/ld: cannot find -lbrotlicommon: No such file or directory

Any help with this issue will be greatly appreciated

`make[1]: Entering directory '/etc/nginx-module-install/nginx-1.18.0'
cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -Wno-deprecated-declarations -I src/core -I src/event -I src/event/module
s -I src/os/unix -I ../ngx_brotli/deps/brotli/c/include -I objs -I src/http -I src/http/modules \
-o objs/addon/filter/ngx_http_brotli_filter_module.o \
../ngx_brotli/filter/ngx_http_brotli_filter_module.c
cc -c -fPIC -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -Wno-deprecated-declarations -I src/core -I src/event -I src/event/module
s -I src/os/unix -I ../ngx_brotli/deps/brotli/c/include -I objs -I src/http -I src/http/modules \
-o objs/ngx_http_brotli_filter_module_modules.o \
objs/ngx_http_brotli_filter_module_modules.c
cc -o objs/ngx_http_brotli_filter_module.so \
objs/addon/filter/ngx_http_brotli_filter_module.o \
objs/ngx_http_brotli_filter_module_modules.o \
-L../ngx_brotli/deps/brotli/c/../out -lbrotlienc -lbrotlicommon -lm \
-shared
/usr/bin/ld: cannot find -lbrotlienc: No such file or directory
/usr/bin/ld: cannot find -lbrotlicommon: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [objs/Makefile:1206: objs/ngx_http_brotli_filter_module.so] Error 1
make[1]: Leaving directory '/etc/nginx-module-install/nginx-1.18.0'
make: *** [Makefile:14: modules] Error 2`

**Comment by malee1975** [comment]
Ah, I think it was the change in make file support!

**Comment by arihantverma** [comment]
@malee1975 could you elaborate on 

> Ah, I think it was the change in make file support!

for a person like me, who doesn't have a lot of context about C ecosystem and make builds? I'm facing the exact same issue. What made it work for you?

**Comment by malee1975** [comment]
@arihantverma This worked, I had to check out an older commit:

...
git clone --recurse-submodules -j8 https://github.com/google/ngx_brotli
# a temp fix for the breaking change introduced in https://github.com/google/ngx_brotli/commit/91155dcf0c5e6972201f72b1a8d0177f75534f72
cd ngx_brotli && git checkout 63ca02abdcf79c9e788d2eedcc388d2335902e52 && cd ..
...

You can read more herem it was [sergeypayu's solution](https://github.com/google/ngx_brotli/commit/91155dcf0c5e6972201f72b1a8d0177f75534f72#commitcomment-129092813)

**Comment by combssm** [comment]
I am running into this issue on an almalinux 9 server.  These are the commands I am running to build brotli nginx dynamic module.
```
wget http://nginx.org/download/nginx-1.24.0.tar.gz
tar xzf nginx-1.24.0.tar.gz
git clone --recurse-submodules https://github.com/google/ngx_brotli
cd ngx_brotli && git checkout 63ca02a && cd ..
cd nginx-1.24.0
./configure --with-compat --add-dynamic-module=../ngx_brotli/
make modules
```

EDIT:
--------
In my case I needed to install the `brotli-devel` package on the system.
