### ISSUE TITLE
''' /tmp/ngx_brotli/filter/ngx_http_brotli_filter_module.c: In function 'ngx_http_brotli_header_filter': 136.9 /tmp/ngx_brotli/filter/ngx_http_brotli_filter_module.c:322:4: error: 'ngx_table_elt_t' has no member named 'next' 136.9   322 |   h->next = NULL; 136.9       |    ^~

### ISSUE THREAD

**Issue by zorka007** [google/ngx_brotli#156]

**Comment by zorka007** [comment]
Hello! Help)

**Comment by nadz-goldman** [comment]
same problem

**Comment by Maxistr1** [comment]
Have the same problem after last changes. Please help

**Comment by jannis-t69** [comment]
Same problem for nginx-1.22.1

**Comment by wyattoday** [comment]
Use the latest NGINX it has security fixes.

See the README for how to build NGINX and ngx_brotli.

**Comment by EduNowell** [comment]
I assume I need to use latest NGINX version, but, Can I do something to use brotli with 1.18.0?

**Comment by TechAdkey** [comment]
I have the same problem, when are you planning to fix this issue or give advice how to fix it

**Comment by gbtec-ext-fernandoquiroga** [comment]
Same issue nginx 1.21.5
