### ISSUE TITLE
Dynamic modules do not compile

### ISSUE THREAD

**Issue by badfiles** [google/ngx_brotli#17]
To compile dynamic modules I had to add rule

```
modules:
	$(MAKE) -f objs/Makefile modules

```
and issue `make modules`.
By default dynamic modules do not compile.

**Comment by PiotrSikora** [comment]
They are built by default, the line you've added is part of generated `Makefile` in `nginx-1.9.11`, see: http://hg.nginx.org/nginx/diff/85dea406e18f/auto/install.

**Comment by badfiles** [comment]
This is the result I get
```
cp  objs/ngx_http_brotli_static_module.so objs/ngx_http_brotli_filter_module.so '/usr/nginx/modules'
cp: cannot stat ‘objs/ngx_http_brotli_static_module.so’: No such file or directory
cp: cannot stat ‘objs/ngx_http_brotli_filter_module.so’: No such file or directory
make[1]: *** [install] Error 1
make[1]: Leaving directory `/src/nginx-1.9.11'
```
objs/addon/src is also empty,
so I have to manually compile modules.
My config 

```
./configure --prefix=/usr/nginx   \
	    --add-dynamic-module=ngx_brotli/ \
	    --with-file-aio \
	    --with-http_ssl_module \
	    --with-http_realip_module \
	    --with-http_gunzip_module \
	    --with-http_gzip_static_module \
	    --with-threads \
	    --with-http_v2_module 

```
(but with `add-module` everything works great)

**Comment by PiotrSikora** [comment]
Weird... Are you using stock `nginx-1.9.11` or patched version? Also, could you post complete output of `./configure --add-dynamic-module=ngx_brotli`, `make` and `make install`?

**Comment by badfiles** [comment]
Last time I tested with rev ba3c2ca21aa5,
having removed this code from module config
`CFLAGS="$CFLAGS -Wno-write-strings"`
I make with `checkinstall`, the output you requested will be in a while.

**Comment by badfiles** [comment]
[out.txt](https://github.com/google/ngx_brotli/files/127988/out.txt)

**Comment by PiotrSikora** [comment]
Thanks! That was helpful. Do you have a name that I should add to the commit message or is "Reported by badfiles on GitHub" fine with you?

**Comment by badfiles** [comment]
yep

**Comment by PiotrSikora** [comment]
http://mailman.nginx.org/pipermail/nginx-devel/2016-February/007909.html

**Comment by raeesiqbal** [comment]
Is this fixed?

**Comment by PiotrSikora** [comment]
I believe it was fixed in http://hg.nginx.org/nginx/rev/cfc3cfa434ec (nginx-1.9.12), why do you ask?

**Comment by raeesiqbal** [comment]
I was going to compile nginx with this module as dynamic. So, just checking if there are any issues I should be aware of.
