### ISSUE TITLE
Need a release

### ISSUE THREAD

**Issue by othree** [google/ngx_brotli#18]
I want to help this module easier to install on OSX using [homebrew](https://github.com/Homebrew/homebrew-nginx).
But before I can do it.
I will need a release like [this](https://github.com/leev/ngx_http_geoip2_module/releases).

Is there any plan for a release?

Thanks

**Comment by denji** [comment]
* https://github.com/google/brotli/issues/326

**Comment by GuillaumeRossolini** [comment]
Hi,

Is it time to revisit this? At least a tag would be nice.

Thanks

**Comment by IlariExove** [comment]
`google/brotli` and `bagder/libbrotli` are both release tagged. So should be `google/ngx_brotli` as well. That would make possible to start packaging this module.

**Comment by khavishbhundoo** [comment]
Any new update on this.....?

**Comment by dvershinin** [comment]
For those in need for RPM, I have packaged the dynamic module with pre-release version of ngx_brotli. It  is usable with official stable Nginx on CentOS 7:

1. Install official Nginx RPM (stable 1.10.3 or 1.12.0)
2. Install extras repo: ````rpm -ivh https://extras.getpagespeed.com/redhat/7/noarch/RPMS/getpagespeed-extras-7-0.el7.gps.noarch.rpm````
3. Install ngx_brotli: ````yum install nginx-module-nbr````

**Comment by denji** [comment]
`ngx_brotli` still alive project?

**Comment by concatime** [comment]
Well, let's hope all together for a miracle.

**Comment by eustas** [comment]
Hopefully, we will have v0.2 in this repo soon.

**Comment by Bacto** [comment]
Hi,
Any news on this? Not having neither a tag or a release is really painful to follow the project.

**Comment by lenovouser** [comment]
@eustas is it now possible to release new tags?
