### ISSUE TITLE
Cannot compile with nginx 1.9.12

### ISSUE THREAD

**Issue by oregapam** [google/ngx_brotli#19]
Hello,

I am on Ubuntu 14.04.4 LTS (GNU/Linux 2.6.32-042stab108.6 x86_64) and used mainline version of nginx source (apt-get source nginx).
The steps that i did:
1. Added "--add-module=/opt/ngx_brotli" to rules file in "nginx/debian" folder.
2. Installed libbrotli from https://github.com/bagder/libbrotli
When I run the "dpkg-buildpackage -b", the compilation is stop at about 99% and gives this error:

...
make[1]: Leaving directory `/opt/nginx-1.9.12'
   dh_makeshlibs
   dh_shlibdeps
dpkg-shlibdeps: error: no dependency information found for /usr/local/lib/libbrotlienc.so.1 (used by debian/nginx/usr/sbin/nginx-debug)
dh_shlibdeps: dpkg-shlibdeps -Tdebian/nginx.substvars debian/nginx/usr/sbin/nginx debian/nginx/usr/sbin/nginx-debug returned exit code 2
make: *** [binary] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2

3. Tried to use ""--add-dynamic-module=/opt/ngx_brotli", it made the compilation, but nginx isn't recognise the "brotli on;" command

Please help!

Thank You,
Mark

**Comment by PiotrSikora** [comment]
Did you try running `ldconfig`? It looks that your system didn't pick up [libbrotli](https://github.com/bagder/libbrotli).

Also, it's not the compilation that breaks, but package building.

**Comment by oregapam** [comment]
I tried, but the problem is still same.

ldconfig -v
...
`/usr/local/lib:
	libbrotlidec.so.1 -> libbrotlidec.so.1.0.0
	libcrypto.so.37 -> libcrypto.so.37.0.0
	libbrotlienc.so.1 -> libbrotlienc.so.1.0.0
	libssl.so.38 -> libssl.so.38.0.0
	libtls.so.10 -> libtls.so.10.0.0`
...

**Comment by Angristan** [comment]
Looks like this https://github.com/google/ngx_brotli/issues/12
It does not work with `dpkg-buildpackage -b`

**Comment by lGuillaume124** [comment]
Hi,

You can add the following line in your ``debian/rules`` file:

```make
override_dh_shlibdeps:                                                          
    dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info
```

**Comment by oregapam** [comment]
Hello,

Thank You, i'll try it later.

BR,
Mark

Az iPhone-omról küldve

2016. ápr. 29. dátummal, 13:25 időpontban Guillaume <notifications@github.com> írta:

**Comment by oregapam** [comment]
Hello,
Sorry for the delay.
I can confirm @lGuillaume124 's solution is working! 👍 

BR, Mark
