### ISSUE TITLE
Ngx_brotli compatibility with Brotli 0.4.0

### ISSUE THREAD

**Issue by xetorixik** [google/ngx_brotli#25]
[Brotli 0.4.0 is released](https://github.com/google/brotli/releases/tag/v0.4.0).
Is Ngx_brotli compatible with Brotli 0.4.0?
(I know it depends on libbrotli, [which has been updated to version 0.40 a few minutes ago](https://github.com/bagder/libbrotli/commit/77a0db1169c300b284a0284f6c31d50cacba8bc9)).

**Comment by eustas** [comment]
Brotli API changed just slightly since December.
0.4.0 release is made because we are planning to roll out next version of encoder API that will be incompatible with 0.3.0 and 0.4.0

**Comment by rugk** [comment]
Why did @badfiles close https://github.com/google/ngx_brotli/pull/26?

**Comment by badfiles** [comment]
Because now it builds just fine,
https://github.com/google/brotli/commit/4a8bb6a2b884e9bf08c508c5f2a8f1feb5e4cd1f

**Comment by rugk** [comment]
Nice, so this issue can be closed, can't it?

**Comment by PiotrSikora** [comment]
Yes.
