### ISSUE TITLE
Yum requires libbrotlienc.so.1 even though the library installed already

### ISSUE THREAD

**Issue by tuannh99** [google/ngx_brotli#27]
Hi,

I installed [libbrotli](https://github.com/bagder/libbrotli) from source successfully, and compiled nginx with param --add-module=[Path/to/ngx_brotli] without any problems.

But when trying to install the result package with yum, I get the error like this:

> --> Processing Dependency: libbrotlienc.so.1()(64bit) for package: nginx-1.10.1-1.el6.ngx.x86_64
> --> Finished Dependency Resolution
> Error: Package: nginx-1.10.1-1.el6.ngx.x86_64 (/nginx-1.10.1-1.el6.ngx.x86_64)
>            Requires: libbrotlienc.so.1()(64bit)
>  You could try using --skip-broken to work around the problem
>  You could try running: rpm -Va --nofiles --nodigest

In fact libbrotlienc.so is already there in the system
#### $ ls -l /usr/local/lib/libbrotlienc*

> -rw-r--r-- 1 root root 7876000 Jun 21 05:53 /usr/local/lib/libbrotlienc.a
> -rwxr-xr-x 1 root root     955 Jun 21 05:53 /usr/local/lib/libbrotlienc.la
> lrwxrwxrwx 1 root root      21 Jun 21 05:53 /usr/local/lib/libbrotlienc.so -> libbrotlienc.so.1.0.0
> lrwxrwxrwx 1 root root      21 Jun 21 05:53 /usr/local/lib/libbrotlienc.so.1 -> libbrotlienc.so.1.0.0
> -rwxr-xr-x 1 root root 3691524 Jun 21 05:53 /usr/local/lib/libbrotlienc.so.1.0.0

Please help.

**Comment by rugk** [comment]
Maybe this issue is similar to the one I had: https://github.com/google/ngx_brotli/issues/23

**Comment by tuannh99** [comment]
@rugk Thank you for your reference.
I could see my library after running ldconfig -p:

> #### sudo ldconfig -p | grep libbrot
	libbrotlienc.so.1 (libc6,x86-64) => /usr/local/lib/libbrotlienc.so.1
	libbrotlienc.so (libc6,x86-64) => /usr/local/lib/libbrotlienc.so
	libbrotlidec.so.1 (libc6,x86-64) => /usr/local/lib/libbrotlidec.so.1
	libbrotlidec.so (libc6,x86-64) => /usr/local/lib/libbrotlidec.so

But yum still produces error:

> Resolving Dependencies
--> Running transaction check
---> Package nginx.x86_64 0:1.10.1-1.el6.ngx will be reinstalled
--> Processing Dependency: libbrotlienc.so.1()(64bit) for package: nginx-1.10.1-1.el6.ngx.x86_64
--> Finished Dependency Resolution
Error: Package: nginx-1.10.1-1.el6.ngx.x86_64 (/nginx-1.10.1-1.el6.ngx.x86_64)
           Requires: libbrotlienc.so.1()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by rugk** [comment]
> I could see my library after running ldconfig -p

Mhh, and running `ldconfig` without any parameters does not help?

**Comment by tuannh99** [comment]
@rugk Yes. I did run it for several times.

**Comment by PiotrSikora** [comment]
This isn't issue with dynamic linker, where `nginx` binary cannot locate `libbrotli`, which `ldconfig` would solve.

This is issue with the packaging, for which you didn't provide any information, and for which you might get better help on `yum`-specific forum and/or mailing list.

**Comment by PiotrSikora** [comment]
Fixed (by bundling Brotli library) in bfd2885b2da4d763fed18f49216bb935223cd34b.
