### ISSUE TITLE
How to use Brotli on the CLI for pre-compiling files to use with brotli_static?

### ISSUE THREAD

**Issue by rugk** [google/ngx_brotli#28]
As you offer server admins to pre-compile files with Brotli and use them with [brotli_static](https://github.com/google/ngx_brotli#brotli_static) it would be nice if you could also explain how to use Brotli on the CLI to pre-compress the files.
Do we need to recompile [libbrotli](https://github.com/bagder/libbrotli) and if so how? /cc @bagder

**Comment by PiotrSikora** [comment]
Use [brotli](https://github.com/google/brotli) command-line tool.

**Comment by rugk** [comment]
This has no instructions how to compile...

**Comment by PiotrSikora** [comment]
`./configure && make`

**Comment by rugk** [comment]
Thanks, that works.
