### ISSUE TITLE
[Error] Dynamic Module

### ISSUE THREAD

**Issue by PabloCariel** [google/ngx_brotli#29]
Hi, Frienda.

Compiler Dynamic Module, error (module "/etc/nginx/modules/ngx_http_brotli_filter_module.so" version 1010001 instead of 1011002 in /etc/nginx/nginx.conf:1)

**Comment by PiotrSikora** [comment]
You're trying to use dynamic module build for NGINX version 1.10.1 with version 1.11.2... This is not going to work with NGINX, since there is no stable ABI or even API, so you need to rebuild dynamic modules for each new version of NGINX.
