### ISSUE TITLE
Ngx_brotli module with a bundled encoder

### ISSUE THREAD

**Issue by xetorixik** [google/ngx_brotli#31]
Is it an idea to deliver the Ngx_brotli module **standalone with a bundled encoder**?
So you get a well tested complete ''all in'' package without external dependencies.
Just like the Cloudflare brotli Nginx module.

Just because:
a lot of different and possibly untested libbrotli's used with Ngx_brotli
Only distro Ubuntu delivers Brotli with their latest release but no one delivers libbrotlienc.
So you need to maintain another package yourself.
Many reported issues or uncertainties are all about loading or linking problems with libbrotlienc or compiling issues.

**Comment by PiotrSikora** [comment]
Fixed in bfd2885b2da4d763fed18f49216bb935223cd34b.

**Comment by xetorixik** [comment]
Thanks @PiotrSikora 
Case closed.
