### ISSUE TITLE
Difference between gzip_static and brotli_static

### ISSUE THREAD

**Issue by hansottowirtz** [google/ngx_brotli#34]
I have a test setup with a `file.js`, `file.js.gz` and `file.js.br`. If add `gzip_static on;` to the `nginx.conf`, the server serves `file.js.gz`, and the `Content-Encoding` header is `gzip`.

If I replace that by `brotli on; brotli_types application/javascript;`, the server serves the on the fly compressed version of `file.js`, and the `Content-Encoding` header is `br`.

However, when I replace that by `brotli_static on;`, the server doesn't serve the `file.js.br`, and there is no `Content-Encoding` header.

Is there any difference between `gzip_static` and `brotli_static`?

**Comment by PiotrSikora** [comment]
What you described should work just fine. Is there anything in the error logs? Perhaps it's an issue with the permissions to the `file.js.br` file?

**Comment by hansottowirtz** [comment]
It was indeed a permissions issue, as I could see in the logs. Sorry to bother, will close this issue. I found a related issue here: https://github.com/google/brotli/issues/410.
