### ISSUE TITLE
libbrotli include files path change

### ISSUE THREAD

**Issue by cujanovic** [google/ngx_brotli#35]
It seems that libbrotli changed the include files path(removed the enc dir) and I can't compile ngx_brotli with nginx anymore.

https://github.com/bagder/libbrotli/commit/5a62fd9e60f07486790d34b9d7f5d879bdd5e1ac
https://github.com/bagder/libbrotli/commit/ff849d1422a618d5a920d6280e9f6005654fd734

**Comment by PiotrSikora** [comment]
Please let me know if [PiotrSikora/ngx_brotli@1252981](https://github.com/PiotrSikora/ngx_brotli/commit/12529813a9f8475718370a19007c7905601a62ad) works for you, I'll merge those changes later today...

**Comment by olemartinorg** [comment]
I can confirm that it works, @PiotrSikora!

**Comment by cujanovic** [comment]
yep, it works now :) thanks @PiotrSikora  :+1:
