### ISSUE TITLE
Sharing MIME type list using GZIP and BROTLI in NGINX

### ISSUE THREAD

**Issue by RehanSaeed** [google/ngx_brotli#38]
I want to enable GZIP and [Brotli](https://github.com/google/ngx_brotli) compression using NGINX. I have to supply each with their own list of MIME types like so in my nginx.conf:

```
gzip_types   text/plain
             text/css
             ...etc;

brotli_types text/plain
             text/css
             ...etc;
```

How can I create a single list of MIME types that can be used by both settings? Also posted on [StackOverflow](https://stackoverflow.com/questions/39827200/sharing-mime-type-list-using-gzip-and-brotli-in-nginx).

**Comment by zxcvbn4038** [comment]
@RehanSaeed You need to give the list to each module seperately.

**Comment by rugk** [comment]
I think you should be able to use variables using set.

**Comment by eustas** [comment]
Either use configuration manager (as recommended on SO), or raise the same question to Nginx developers.
The bigger problem is - currently in the Nginx universe there is only one compressor - gzip. We have to convince Nginx developers to change that. A lot of things could be reused, if we define "compressor API" and make gzip and brotli just compression engines...
