### ISSUE TITLE
ngx_brotli + ngx_pagespeed

### ISSUE THREAD

**Issue by centminmod** [google/ngx_brotli#4]
ngx_brotli might have broken ngx_pagespeed support over https https://github.com/pagespeed/ngx_pagespeed/issues/1021 ?

Seeing as both Google projects, hope to see them working nicely together :)

**Comment by PiotrSikora** [comment]
Thanks for the report! I'm going to close this, since it's tracked in pagespeed/ngx_pagespeed#1021 and it needs to be fixed there.
