### ISSUE TITLE
This isn’t compiling with nginx 1.11.6

### ISSUE THREAD

**Issue by 872517414** [google/ngx_brotli#41]
> cc1: all warnings being treated as errors
objs/Makefile:1297: recipe for target 'objs/addon/src/ngx_http_brotli_filter_module.o' failed
make[1]: *** [objs/addon/src/ngx_http_brotli_filter_module.o] Error 1
make[1]: Leaving directory '/root/lnmp1.3/src/nginx-1.11.6'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

Some one with 1.9.11 #16

**Comment by 872517414** [comment]
with `--with-cc-opt=-Wno-deprecated-declarations` was ok.

**Comment by PiotrSikora** [comment]
Fixed (by bundling Brotli library) in bfd2885b2da4d763fed18f49216bb935223cd34b.
