### ISSUE TITLE
Vary Accept-Encoding header

### ISSUE THREAD

**Issue by Lofesa** [google/ngx_brotli#44]
Hi
Can this module add an "vary: accept-encoding" same as gzip module do? Can this be considered an enhancement? Is this feasible?

Thx in advance

**Comment by dvershinin** [comment]
+1. The module should basically have the same option as gzip, i.e. ```brotly_vary on;```

**Comment by concatime** [comment]
+1. I really want 100% on GTmetrix ;)

**Comment by ahmed-sigmalux** [comment]
Please add this setting.

**Comment by eustas** [comment]
Now module sets "gzip_vary = 1", so nginx core should take care of setting the header.

**Comment by alanZhou56** [comment]
> Now module sets "gzip_vary = 1", so nginx core should take care of setting the header.
 Hi @eustas 
Do you mean that as long as Nginx supports both Brotli and Gzip compression algorithms simultaneously, it must return a Vary header, right?
