### ISSUE TITLE
invalid number of arguments in "brotli_static" directive

### ISSUE THREAD

**Issue by Kirkis** [google/ngx_brotli#5]
Hi,

I just built rev-557486 as a module on an nginx-1.8.0, then added the following line inside a server context (ssl):
```
brotli_static on
```
nginx stop then nginx start gives me the following:
```
nginx: [emerg] invalid number of arguments in "brotli_static" directive in ...
```
What am I doing wrong?
Thanks,

**Comment by PiotrSikora** [comment]
Hi,
assuming that you pasted whole line, you're missing semicolon at the end, it should be:

    brotli_static on;

**Comment by Kirkis** [comment]
No????
Yes...
Thanks, it works. Sorry for the bother.
