### ISSUE TITLE
Inconsistency content-encoding header if both brotli and gzip was enabled

### ISSUE THREAD

**Issue by draskolnikova** [google/ngx_brotli#50]
Hello!

I got unexpected behavior when enable this directive:

```
... [truncated] ...
    brotli on;
    brotli_types text/css text/javascript application/json application/javascript;
    brotli_comp_level 9;

    gzip  on;
    gzip_vary  on;
    gzip_static on;
    gzip_comp_level 6;
    gzip_proxied any;
    gzip_disable "MSIE [1-6]\.(?!.*SV1)";
    ignore_invalid_headers on;
    gzip_types application/xml+rss;
    gzip_types application/ecmascript;
    gzip_types application/json;
    gzip_types application/javascript;
    gzip_types application/pdf;
    gzip_types application/postscript;
    gzip_types application/x-javascript;
    gzip_types image/svg+xml;
    gzip_types text/javascript;
    gzip_types text/css;
    gzip_types text/csv;
    gzip_types text/plain;
    gzip_types text/xml;
    gzip_http_version 1.1;
... [truncated] ...
```

Clients can got `br` or `gzip` randomly, but it's OK with Google Chrome and Mozilla Firefox. But fails against OSX Safari and Mobile Safari (iOS Device). 

![whatsapp image 2017-04-13 at 13 01 13](https://cloud.githubusercontent.com/assets/3316535/24995456/13799a6c-2059-11e7-84e2-42c8d2663458.jpeg)

Brotli response header was 

```
cache-control:max-age=300
content-encoding:br
content-type:text/css
date:Thu, 13 Apr 2017 07:55:51 GMT
expires:Thu, 13 Apr 2017 08:00:35 GMT
last-modified:Wed, 01 Mar 2017 08:30:42 GMT
server:dmnQ
status:200
vary:Accept-Encoding
x-cache:HIT
x-view:desktop
```

Gzip response header was 

```
cache-control:max-age=300
content-encoding:gzip
content-type:text/css
date:Thu, 13 Apr 2017 07:58:09 GMT
expires:Thu, 13 Apr 2017 08:02:56 GMT
last-modified:Wed, 01 Mar 2017 08:30:42 GMT
server:dmnQ
status:200
vary:Accept-Encoding
x-cache:HIT
x-view:desktop
```

Is it normal?

**Comment by PiotrSikora** [comment]
Are you using a CDN, by any chance?

**Comment by draskolnikova** [comment]
@PiotrSikora no, i am not using any cdn to host the content. I just found the problem why the header always not valid against OSX Safari.

The problem was triggered with `proxy_ignore_headers Cache-Control Expires Vary`. Safari can't determine whether encoding came in `gzip` or `brotli`, but Firefox and Chrome are normal even `Vary` are ignored in the header. :)

Phew! Sorry for bother your weekend.

**Comment by PiotrSikora** [comment]
Is the content cached anywhere? Because if you ignore `Vary` header, then cache will use whatever version is stored in the cache (regardless of whether it's compressed with `gzip` or `brotli`).

Sounds like you have version compressed with `brotli` in the cache, and it's always served, because you ignore `Vary` header.

**Comment by draskolnikova** [comment]
@PiotrSikora yes you're right, is there any best practice? Because if I didn't ignore vary header, the contents was error on safari (ios and osx). Sorry for very late response.

**Comment by eustas** [comment]
Respect the vary header. I believe, today most proxies / caches know how to deal with that.
https://blog.stackpath.com/accept-encoding-vary-important/
