### ISSUE TITLE
Brotli doesn't work with Firefox and SPDY

### ISSUE THREAD

**Issue by Kirkis** [google/ngx_brotli#6]
Hi,
Could you please provide a sample configuration to serve brotli files? Here are my test files:
```
static# ls -alh www-en.css*
-rw-r--r-- 1 nginx www-data 212K 2015-10-15 19:51 www-en.css
-rw-r--r-- 1 nginx www-data  28K 2015-10-15 19:51 www-en.css.br
-rw-r--r-- 1 nginx www-data  35K 2015-10-15 19:51 www-en.css.gz
static# nginx -V
nginx version: nginx/1.8.0
built by gcc 4.7.2 (Debian 4.7.2-5)
built with OpenSSL 1.0.2d 9 Jul 2015
TLS SNI support enabled
configure arguments: --with-cc-opt=-I/usr/local/include --with-ld-opt=-L/usr/local/lib --with-cpu-opt=amd64 --sbin-path=/usr/local/sbin --with-http_ssl_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_gunzip_module --with-http_stub_status_module --with-http_gzip_static_module --with-http_spdy_module --conf-path=/etc/nginx/nginx.conf --add-module=/usr/local/src/ngx_brotli-557486
```
Here is the relevant part of my config (this server block listens on "443 ssl spdy") :
```
	location ~ ^/static/.* {
		gzip_static off;
		gzip off;
		gzip_proxied off;
		brotli_static on;
		add_header Cache-Control "public";
	}
```
But it does not seem to catch the .br file:
```
Accept-Ranges: bytes
Cache-Control: max-age=31536000, public
Content-Length: 216945
Content-Type: text/css
Date: Fri, 16 Oct 2015 06:14:29 GMT
Etag: "561fe7a5-34f71"
Expires: Sat, 15 Oct 2016 06:14:29 GMT
Last-Modified: Thu, 15 Oct 2015 17:51:33 GMT
Server: nginx
X-Firefox-Spdy: 3.1
```
However, with "gzip_static on" it does serve the .gz file:
```
Cache-Control: max-age=31536000, public
Content-Encoding: gzip
Content-Length: 34836
Content-Type: text/css
Date: Fri, 16 Oct 2015 06:23:30 GMT
Etag: "561fe7a5-8814"
Expires: Sat, 15 Oct 2016 06:23:30 GMT
Last-Modified: Thu, 15 Oct 2015 17:51:33 GMT
Server: nginx
X-Firefox-Spdy: 3.1
```
What am I doing wrong? Or is my .br file broken? I checked it with a command like this and I got the expected CSS rules, so I guess the compressed file is ok:
```
cat www-en.css.br | /usr/local/src/brotli-0.2.0/tools/bro --verbose --decompress | tail
```

**Comment by Kirkis** [comment]
UPDATE
When deactivating spdy module, it all works fine:
```
Cache-Control: max-age=31536000, public
Connection: keep-alive
Content-Encoding: br
Content-Length: 28628
Content-Type: text/css
Date: Fri, 16 Oct 2015 06:45:54 GMT
Etag: "561fe7a5-6fd4"
Expires: Sat, 15 Oct 2016 06:45:54 GMT
Keep-Alive: timeout=10
Last-Modified: Thu, 15 Oct 2015 17:51:33 GMT
Server: nginx
Vary: Accept-Encoding
```

**Comment by PiotrSikora** [comment]
That's [a bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1215724), as it doesn't send "Accept-Encoding" header when using SPDY (Developer Tools display it, but Firefox doesn't send it)... luckily, it works fine with HTTP/2.

SPDY/3.1 request (as displayed in Firefox):

    Host: localhost:8080
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    Accept-Language: en-US,en;q=0.5
    Accept-Encoding: gzip, deflate, br
    Connection: keep-alive
    Pragma: no-cache
    Cache-Control: no-cache

SPDY/3.1 request (as seen by nginx):

    spdy http request line: "GET / HTTP/1.1"
    spdy http header: "host: localhost:8080"
    spdy http header: "user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0"
    spdy http header: "accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    spdy http header: "accept-language: en-US,en;q=0.5"
    spdy http header: "cache-control: no-cache"
    spdy http header: "pragma: no-cache"

SPDY/3.1 response (as displayed in Firefox):

    Content-Encoding: gzip
    Content-Type: text/html
    Date: Fri, 16 Oct 2015 20:07:12 GMT
    Etag: W/"55f75295-28e0"
    Last-Modified: Mon, 14 Sep 2015 23:04:53 GMT
    Server: nginx/1.9.4
    X-Firefox-Spdy: 3.1

HTTP/2 request (as displayed in Firefox):

    Host: localhost:8080
    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    Accept-Language: en-US,en;q=0.5
    Accept-Encoding: gzip, deflate, br
    Connection: keep-alive
    Pragma: no-cache
    Cache-Control: no-cache

HTTP/2 request (as seen by nginx):

    http2 http header: "user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0"
    http2 http header: "accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    http2 http header: "accept-language: en-US,en;q=0.5"
    http2 http header: "accept-encoding: gzip, deflate, br"
    http2 http header: "pragma: no-cache"
    http2 http header: "cache-control: no-cache"
    http2 http request line: "GET / HTTP/2.0"

HTTP/2 response (as displayed in Firefox):

    Content-Encoding: br
    Content-Type: text/html
    Date: Fri, 16 Oct 2015 20:01:38 GMT
    Etag: W/"55f75295-28e0"
    Last-Modified: Mon, 14 Sep 2015 23:04:53 GMT
    Server: nginx/1.9.5
    Vary: Accept-Encoding
    X-Firefox-Spdy: h2

**Comment by Angristan** [comment]
How do you add `Content-Encoding: br` ?
