### ISSUE TITLE
Test Brotli compression

### ISSUE THREAD

**Issue by papiveron** [google/ngx_brotli#61]
Hi,

Please someone here could tell me how to test brotli module?

I compiled and loaded the module in static and dynamic, when I speficy `br` format to my user agent for dynamic compression it does notthing, the returned file is not compressed.

I also used brotli on my web server to comprresse files, I place them in my document root with the `br` extension, and when I request these files the nginx server returns the uncompressed version.

I don't exactly know how to test and make sure brotli works fine on my server.

Please help.

Cheers,
Eugène NG

**Comment by papiveron** [comment]
Hello,

Sorry it works, I was requesting the wrong server.

Now I have another issue, I don't see `br` neither in my firefox nor in my chrome `Accept-Encoding` header....

What could be the reason please?
Thank you.

Regards,
Eugène NG

**Comment by tspicer** [comment]
It only works with HTTPS so if you are just using HTTP for your tests you wont see it. That took me awhile to figure out.

**Comment by papiveron** [comment]
Ah I see...

Thank you guy, I just figure out, the browser only add `br` format for `https`requests?

Cheer,
Eugène NG

**Comment by tspicer** [comment]
Yes, just `https` requests

**Comment by eustas** [comment]
See https://github.com/google/ngx_brotli/blob/master/script/.travis-test.sh
