### ISSUE TITLE
ngx_brotli clashes with macports brotli

### ISSUE THREAD

**Issue by eiked** [google/ngx_brotli#64]
error: use of undeclared identifier 'kBrotliMinWindowBits'

on macOS/OSX with macports brotli installed

ngx_brotli/src/ngx_http_brotli_filter_module.c
`#include <brotli/encode.h>
`
includes
`/opt/local/include/brotli/encode.h
`
instead of
`./deps/brotli/include/brotli/encode.h
`

I suggest that should be changed to:
`#include "brotli/encode.h"
`

and we also have to change the CFLAGS to read
`-iquote ../ngx_brotli/deps/brotli/include
`
instead of
`-I ../ngx_brotli/deps/brotli/include
`
which comes from ngx_brotli/config
`ngx_module_incs="$brotli/include"
`

which might actually be a problem in the nginx configure

**Comment by eiked** [comment]
see also
https://trac.nginx.org/nginx/ticket/1465#ticket

**Comment by eiked** [comment]
https://trac.macports.org/ticket/55729#ticket

**Comment by eustas** [comment]
FWIW: most likely, problem is solved in https://github.com/eustas/ngx_brotli
