### ISSUE TITLE
Make it clear that this repo is unmaintained

### ISSUE THREAD

**Issue by wjessop** [google/ngx_brotli#69]
Perhaps a simple message at the top of the README pointing at what seems like the most active fork:

https://github.com/eustas/ngx_brotli

It would save people who are trying to use this time in the future.

**Comment by eustas** [comment]
It is maintained again =)

**Comment by wjessop** [comment]
Yay! Any thoughts on pulling in the changes from the @eustas branch, or on plans for the future? I build brotli nginx builds for clients every once in a while so it's handy to know.

**Comment by eustas** [comment]
Actually this is already done =) eustas/ngx_brotli is archived now.
Future development will be done in google/ngx_brotli.

**Comment by eustas** [comment]
First - try to reduce the number of issues to zero. Closed all non-relevant / fixed issues, going to work on remaining ones =)

**Comment by wjessop** [comment]
Great, so happy to see stuff happening, thanks!

**Comment by HansVanEijsden** [comment]
Thank you very much, @eustas !

**Comment by iamstarkov** [comment]
> Actually this is already done =) eustas/ngx_brotli is archived now.
> Future development will be done in google/ngx_brotli.

@eustas where can I find the discussion about merging your fork back to the upstream?
