### ISSUE TITLE
What could cause the module not to load?

### ISSUE THREAD

**Issue by Kirkis** [google/ngx_brotli#7]
Hi,
Thanks to you, I got nginx to work with this module on one host. However, it won't work on another host with nginx 1.8.0 or 1.9.6:
```
nginx: [emerg] unknown directive "brotli_static"
```
Here is my configure line:

```
./configure --with-cc-opt=-I/usr/local/include --with-ld-opt=-L/usr/local/lib --with-cpu-opt=amd64 --sbin-path=/usr/local/sbin --with-http_ssl_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_gunzip_module --with-http_stub_status_module --with-http_gzip_static_module --add-module=/usr/local/src/ngx_brotli-557486 --conf-path=/etc/nginx/nginx.conf
checking for OS
 + Linux 3.10.23-xxxx-std-ipv6-64 x86_64
checking for C compiler ... found
 + using GNU C compiler
 + gcc version: 4.7.2 (Debian 4.7.2-5)
```
```
configuring additional modules
adding module in /usr/local/src/ngx_brotli-557486
checking for Brotli library ... found
 + ngx_brotli was configured
```
Once the build is complete, the "nginx -t" command works fine, but on startup I get an error on brotli_static directive. For the moment I'll only be using this directive inside a location block (serving files pre-compressed with the bro utility), like this:
```
brotli_static on;
```
So I should not need badger's libbrotli, but I built it anyway:
```
ldd /usr/local/sbin/nginx
        linux-vdso.so.1 =>  (***)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (***)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (***)
        libbrotlienc.so.1 => /usr/local/lib/libbrotlienc.so.1 (***)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (***)
        libpcre.so.1 => /usr/local/lib/libpcre.so.1 (***)
        libssl.so.1.0.0 => /usr/local/lib/libssl.so.1.0.0 (***)
        libcrypto.so.1.0.0 => /usr/local/lib/libcrypto.so.1.0.0 (***)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (***)
        libz.so.1 => /usr/local/lib/libz.so.1 (***)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (***)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (***)
        /lib64/ld-linux-x86-64.so.2 (***)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (***)
```
Do you know how I can debug this? I'm sure it has nothing to do with your module but most probably something is broken on my setup.
Thanks,

**Comment by PiotrSikora** [comment]
Since `nginx -t` works fine, it means that the module is compiled correctly.

My guess is that either your "startup" script is calling different binary or that you're trying to reload already running binary that doesn't have brotli support built-in.

Maybe try using full path to nginx?

    /usr/local/sbin/nginx -t
    /usr/local/sbin/nginx

**Comment by Kirkis** [comment]
How did I not see that before... Thanks, that solved it.
Nice work, by the way.
