### ISSUE TITLE
Compression Performance

### ISSUE THREAD

**Issue by ZecaStevenson** [google/ngx_brotli#70]
Thank you for creating the algorithm and for creating this plugin.

I have used gzip compression with Apache and with Nginx for several years, but Brotlei is new to me. It seems that the algorithm decompress files at the same speed as gzip (aprox), but its compression time is much higher than gzip's.

I don't know how this plugin works, but for cached content, this is what I think it could make sense:

1. upon the 1st request, check for an already compressed file (.br)
2. if it exists and it's not expired, serve it.
3. if it does not exist, start compressing the file, but serve a gzip version (and related HTTP headers) of it for this and all subsequent requests, till the Brotlei file is compressed.

So I guess I am requesting a feature: use gzip till the brotlei compression is completed.

Cheers,
Zéca

**Comment by blikenoother** [comment]
you can also generate the compressed file (.br) at the time of your deployment process for static files like javascript and css

check [this article](https://medium.com/@blikenoother/nginx-brotli-compression-developed-by-google-which-helps-reducing-18-latency-over-gzip-d9f5f5f28b92) for more detail

**Comment by ZecaStevenson** [comment]
Thanks for the reply, and for the article URL.

It seems like I could use level 4-5 compression for the dynamic content, in which case, the plugin could use level 11 compression to create the .br file in the cache filesystem (in the background), and once ready, replace the original file created with level 4-5 compression...

**Comment by eustas** [comment]
Still, it is better to do precompression as a part of deployment, to avoid unnecessary caching.
