### ISSUE TITLE
Error with level-3 compression on some HTML

### ISSUE THREAD

**Issue by sunnybear** [google/ngx_brotli#84]
Hello. Noticed that some HTML (example attached) is broken with brotli_comp_level 3 optimization (nor 2-, nor 4+, exactly 3). With attached HTML under brotli compression level 3 there is no symbols after line 527, position 61. With level 2 or level 4 - the whole document is correctly compressed.
[brotli-3.html.txt](https://github.com/google/ngx_brotli/files/3585397/brotli-3.html.txt)

**Comment by eustas** [comment]
Hello.
Could you check if it is fixed after #82?

**Comment by sunnybear** [comment]
No, it's not fixed. Issue can be reproduced with the last git source code.
Maybe it's related to brotli 1.0.7 itself.

**Comment by eustas** [comment]
I'll check it on Monday. Thanks for the report.

**Comment by eustas** [comment]
Works for me... Could you create a PR that updates...
 * `scripts/.travis-before-test.sh` (fetch the file, similar to war-and-piece)
 * `scripts/test.conf` (set compression level)
 * `scripts/.travis-test.sh`(new test case)
... that would demonstrate the problem? Thanks.

**Comment by eustas** [comment]
Sorry, false start. The fix is #83, and it is not yet landed.

**Comment by eustas** [comment]
Landed

**Comment by sunnybear** [comment]
Thank you. It seems issue has been resolved. Will check on production in a month, this can be closed right now.
