### ISSUE TITLE
libbrotlienc.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kakigorimochi** [google/ngx_brotli#86]
Loading this alone has no problem:
**load_module modules/ngx_http_brotli_static_module.so;**

While loading this give me an error when I do: "**nginx -t**"
**load_module modules/ngx_http_brotli_filter_module.so;**

> nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_brotli_filter_module.so" failed (libbrotlienc.so.0: cannot open shared object file: No such file or directory)

So I ran this command to check: "ls -l /usr/local/lib/libbrotlienc*"
![image](https://user-images.githubusercontent.com/16938949/66038422-ab8a1180-e544-11e9-9d0e-d2ba4ed122b6.png)

I don't know where I went wrong. 
As the nginx ./configure, make and make install ran successfully after I installed https://github.com/bagder/libbrotli since I was missing **libbrotlienc.**

**Comment by kakigorimochi** [comment]
I've seen answers like running "**ldconfig**" alone but it doesn't really do anything when I entered it and ran "nginx -t" again or am I missing steps?

**Comment by kakigorimochi** [comment]
As per searching for answers on my issue, it was resolved by Olivier S's approach to the problem.

> You can edit the file **/etc/ld.so.conf** and add your path **/usr/local/lib** to it or create a new file in /etc/ld.so.conf.d/ like **/etc/ld.so.conf.d/usrlocal.conf** and put only the following line in it:
> 
> **/usr/local/lib**
> 
> Then run ldconfig -v as root, and you're done.


Reference: https://serverfault.com/questions/372987/centos-usr-local-lib-system-wide-ld-library-path

I'm not sure if this is a right way to address the issue. Please, leave any comment or suggestions. Thank you!

**Comment by eustas** [comment]
IMHO, the right way is to have statically linked `ngx_http_brotli_filter_module.so`.
I know, I'm going to be blamed by security folks, but IMHO it is better to rely on fresh trusted builds than on library updates.
