### ISSUE TITLE
symlinks not followed

### ISSUE THREAD

**Issue by tetzank** [google/ngx_brotli#9]
brotli_static does not follow symlinks like gzip_static does.

I'm not sure what's going on here. If the request path needs to follow a symlink, .br files are never picked up, not even with always. .gz files are used without a problem. If i place all files directly in the root folder, not following any symlinks, brotli_static starts to work fine.

I should probably stop using symlinks. Still an odd behaviour.

**Comment by PiotrSikora** [comment]
I cannot replicate this, symlinks work fine for me.

Are the permissions correct? Is there anything in the error.log? Could you post more details about symlinks and their destination (ideally with all permissions along the way)?

**Comment by tetzank** [comment]
Oh, boy. You're right. The file permission of the .br file wasn't correct. Not sure how i missed that. The brotli encoder just sets 600 and i forgot to change it.

Sorry for the noise and thanks for this nice module.
